theme: jekyll-theme-cayman
title: Call4Buddies
description:
    en: Do you know someone who could participate in our event?
    es: ¿Conoces a alguien que podría participar en nuestro evento?
    ca: Coneixes a alguna persona que podría participar al nostre event?
plugins:
  - jekyll-redirect-from
